// <auto-generated />
using InokerWebApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace InokerWebApp.Migrations
{
    [DbContext(typeof(InokerwebappdbContext))]
    partial class InokerwebappdbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InokerWebApp.Models.Collection", b =>
                {
                    b.Property<int>("CollectionId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("CollectionId");

                    b.ToTable("Collection");
                });

            modelBuilder.Entity("InokerWebApp.Models.Model", b =>
                {
                    b.Property<int>("ModelId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(60);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("ModelId");

                    b.ToTable("Model");
                });

            modelBuilder.Entity("InokerWebApp.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Product");

                    b.Property<int>("CollectionId");

                    b.Property<int>("Height");

                    b.Property<int>("ModelId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<byte[]>("Photo1");

                    b.Property<byte[]>("Photo2");

                    b.Property<decimal>("Price");

                    b.Property<int>("Stock");

                    b.Property<int>("Width");

                    b.HasKey("ProductId");

                    b.HasIndex("CollectionId");

                    b.HasIndex("ModelId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("InokerWebApp.Models.Product", b =>
                {
                    b.HasOne("InokerWebApp.Models.Collection", "Collection")
                        .WithMany("Products")
                        .HasForeignKey("CollectionId")
                        .HasConstraintName("FK_Product_Collection");

                    b.HasOne("InokerWebApp.Models.Model", "Model")
                        .WithMany("Products")
                        .HasForeignKey("ModelId")
                        .HasConstraintName("FK_Product_Model");
                });
#pragma warning restore 612, 618
        }
    }
}
